# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):

    obj = bld.create_ns3_program('first', ['vanetsim'])
    obj.source = 'first.cc'

    obj = bld.create_ns3_program('vanet-example', ['vanetsim'])
    obj.source = 'vanet-example.cc'